"""
End-to-end x402 demo.

Spins up the control plane in a background thread, then walks the
full x402 round-trip with `curl`-equivalent HTTP calls. The
point of this script is to make the protocol visible: you can
see the 402 response with its invoice headers, then the retry
with a payment proof, then the 200 with the receipt.

Run as:

    python scripts/x402_demo.py

Or, for a more realistic flow that goes through a real Unix
socket, see `scripts/x402_demo_curl.sh` (not generated by
default — only useful if you want to use real `curl`).
"""
from __future__ import annotations

import json
import sys
import threading
import time
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from fastapi.testclient import TestClient  # noqa: E402

from services.control_plane.api import create_app  # noqa: E402
from services.payments import (  # noqa: E402
    H_INVOICE,
    H_PAYER,
    H_TX,
)


def _request(
    client: TestClient,
    method: str,
    path: str,
    headers: dict[str, str] | None = None,
) -> tuple[int, "httpx.Headers", dict]:
    import httpx  # local import; not part of the public dep list
    r = client.request(method, path, headers=headers or {})
    body: dict = {}
    if r.content:
        try:
            body = r.json()
        except Exception:
            body = {"_raw": r.text}
    # `r.headers` is an httpx.Headers instance: case-insensitive
    # lookup, which matches the X-Payment-* constants.
    return r.status_code, r.headers, body


def main() -> int:
    print("=" * 70)
    print("  x402 end-to-end demo")
    print("=" * 70)
    print()

    app = create_app()
    aid = "atm_demo_x402"
    resource = "research"
    payer = "0x" + "d" * 40

    with TestClient(app) as client:
        # Step 1: First request — no payment proof, expect 402.
        print("Step 1: client requests /pay/research with no payment proof")
        print("-" * 70)
        status, headers, body = _request(client, "POST", f"/v1/x402/{aid}/pay/{resource}")
        print(f"  → status: {status}")
        print(f"  → X-Payment-Invoice: {headers.get(H_INVOICE)}")
        print(f"  → X-Payment-Amount : {headers.get('X-Payment-Amount')} (micro-USDC)")
        print(f"  → X-Payment-Address: {headers.get('X-Payment-Address')[:20]}…")
        print(f"  → X-Payment-Chain : {headers.get('X-Payment-Chain')}")
        print(f"  → X-Payment-Expires-At: {headers.get('X-Payment-Expires-At')}")
        print()
        assert status == 402, f"expected 402, got {status}"
        invoice_id = headers[H_INVOICE]

        # Step 2: Bad payment proof — short hash. Expect 402.
        print("Step 2: client retries with a malformed payment proof")
        print("-" * 70)
        bad_headers = {
            H_INVOICE: invoice_id,
            H_TX: "0xshort",
            H_PAYER: payer,
        }
        status, _, _ = _request(client, "POST", f"/v1/x402/{aid}/pay/{resource}", bad_headers)
        print(f"  → status: {status} (verifier rejected the proof)")
        assert status == 402
        print()

        # Step 3: Good payment proof. Expect 200.
        print("Step 3: client retries with a valid payment proof")
        print("-" * 70)
        good_headers = {
            H_INVOICE: invoice_id,
            H_TX: "0x" + "a" * 64,
            H_PAYER: payer,
        }
        status, headers, body = _request(
            client, "POST", f"/v1/x402/{aid}/pay/{resource}", good_headers
        )
        print(f"  → status: {status}")
        print(f"  → receipt: invoice_id={body['invoice_id']}, tx={body['tx_hash'][:18]}…")
        print(f"  → amount:  {body['amount_micro']} micro-USDC = ${body['amount_major']} USDC")
        print(f"  → resource: {body['resource']}")
        assert status == 200
        assert body["paid"] is True
        print()

        # Step 4: Stats show 1 receipt, 1 invoice.
        print("Step 4: operator inspects x402 stats")
        print("-" * 70)
        status, _, body = _request(client, "GET", f"/v1/x402/{aid}/stats")
        print(f"  → status: {status}")
        print(f"  → invoices: {body['invoices']}")
        print(f"  → receipts: {body['receipts']}")
        print(f"  → wallet:   {body['wallet_address'][:20]}…")
        print(f"  → chain:    {body['chain']}")
        print(f"  → token:    {body['token']}")
        assert status == 200
        assert body["receipts"] == 1
        print()

        # Step 5: Idempotency — retry the same proof, no double-credit.
        print("Step 5: client retries the same proof (idempotency check)")
        print("-" * 70)
        status, _, body = _request(
            client, "POST", f"/v1/x402/{aid}/pay/{resource}", good_headers
        )
        print(f"  → status: {status} (still 200 — same receipt returned)")
        status, _, stats = _request(client, "GET", f"/v1/x402/{aid}/stats")
        print(f"  → receipts: {stats['receipts']} (still 1, no double-credit)")
        assert stats["receipts"] == 1
        print()

    print("=" * 70)
    print("  Demo complete — x402 round-trip works end-to-end")
    print("=" * 70)
    return 0


if __name__ == "__main__":
    sys.exit(main())
